---
  - hosts: word_press
    become: True
    become_user: root
    tasks:
    - name: download apache exporter
      get_url:
        url: https://github.com/Lusitaniae/apache_exporter/releases/download/v0.10.1/apache_exporter-0.10.1.linux-amd64.tar.gz
        dest: /tmp
    - name: unarchive apache exporter
      unarchive:
        remote_src: yes
        src: /tmp/apache_exporter-0.10.1.linux-amd64.tar.gz
        dest: /tmp
    - name: move apache exporter to /usr/local/bin
      copy:
        src: /tmp/apache_exporter-0.10.1.linux-amd64/apache_exporter
        dest: /usr/local/bin/apache_exporter
        remote_src: yes
        owner: root
        group: root
        mode: 0755
    - name: install unit file to systemd
      template:
        src: exports/apache_exporter.j2
        dest: /etc/systemd/system/apache_exporter.service
        owner: root
        group: root
        mode: 0600
    - name: configure systemd to use service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: started
        name: apache_exporter.service
    - name: Enable service httpd and ensure it is not masked
      ansible.builtin.systemd:
        name: apache_exporter
        enabled: yes

