---
- hosts: all
  become: true
  tasks:
    - name: Update cache 
      apt:
       update_cache: yes
         
    - name: Upgrade all packages on servers
      apt: 
        name: "*"
        state: latest

    - name: Install nfs client on all instances.
      action: apt pkg=nfs-common state=present

    - name: Copy host file to /etc/hosts
      copy:
        src: ./exports/hosts
        dest: /etc/hosts 
## install nfs-common on all servers
##mount 192.168.199.14:/mnt/nfs_share /home/ubuntu/test/
- import_playbook: "fileserver.yml"
- import_playbook: "mountnfs.yml"
- import_playbook: "fileserver.yml"
- import_playbook: "master.yml"
