---
- hosts: all
  become: true
  tasks:   
    - name: Copy host file to /etc/hosts
      copy:
        src: ./exports/hosts
        dest: /etc/hosts 
- import_playbook: "fileserver.yml"
- import_playbook: "mountnfs.yml"
- import_playbook: "db.yml"
- import_playbook: "loadbalancer.yml"

