---
- hosts: all
  become: true
  tasks:
    - name: Update cache 
      apt:
       update_cache: yes
         
    - name: Upgrade all packages on servers
      apt: 
        name: "*"
        state: latest
    - name: Install nfs client on all instances.
      action: apt pkg=nfs-common state=present

- import_playbook: "fileserver.yml"
- import_playbook: "master.yml"
