---
- hosts: all
  become: true
  gather_facts: no # important to not gather_facts when waiting for connection, we do that later.
  tasks:
  
    - name: Wait for system to become reachable
      wait_for_connection:

    - name: Gather facts for first time
      setup:

    - name: Copy host file to /etc/hosts
      copy:
        src: ./exports/hosts.j2
        dest: /etc/hosts

- import_playbook: "fileserver.yml"
- import_playbook: "db.yml"
- import_playbook: "loadbalancer.yml"
- import_playbook: "wordpress.yml"
- import_playbook: "node_exporter.yml"
- import_playbook: "apache_exporter.yml"
- import_playbook: "prometheus.yml"

