#https://stackoverflow.com/questions/55511770/detect-and-mount-filesystem-in-ansible
#https://advishnuprasad.com/blog/2016/03/29/setup-nfs-server-and-client-using-ansible/
---
- hosts: fileserver
  become: true
  tasks:     
    - name: Create a file system on deviece id(usally sdb)
      community.general.filesystem:
        fstype: ext4
        dev: "{{device_id}}"
    - name: Mount File System
      mount:
        path: "{{mount_path}}"
        src: "{{device_id}}"
        fstype: ext4
        state: mounted
    - name: Change owner to username you login and chmod as required
      file:
        path: "{{mount_path}}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0700
    - name: install nfs server
      action: apt pkg=nfs-kernel-server state=present
    - name: Add Servers to /etc/exports
      template: src=./exports/nfs_exports.j2 dest=/etc/exports owner=root group=root
    - name: restart nfs server
      service: name=nfs-kernel-server state=restarted