#https://stackoverflow.com/questions/55511770/detect-and-mount-filesystem-in-ansible
#https://advishnuprasad.com/blog/2016/03/29/setup-nfs-server-and-client-using-ansible/
---
- hosts: fileserver
  become: true
  tasks:
    - name: Create a file system on deviece id(usally sdb)
      community.general.filesystem:
        fstype: ext4
        dev: "{{device_id}}"
    - name: Mount File System
      mount:
        path: "{{mount_path}}"
        src: "{{device_id}}"
        fstype: ext4
        state: mounted
    - name: Change owner to username you login and chmod as required
      file:
        path: "{{mount_path}}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0700
    - name: install nfs server
      action: apt pkg=nfs-kernel-server state=present
    - name: Add Servers to /etc/exports
      template: src=./exports/nfs_exports.j2 dest=/etc/exports owner=root group=root
    - name: restart nfs server
      service: name=nfs-kernel-server state=restarted

    - name: Creates www  directory for html files.
      file:
        path: "{{ mount_path }}"
        state: directory
        mode: '0755'

    - name: install acme wordpress and unarchive it
      unarchive:
        src: https://github.com/2dv514/syllabus/blob/master/examination/part_2/acme_wordpress_files_and_data.tar.gz?raw=true
        dest: "{{ mount_path }}"
        remote_src: yes

    - name: Unzip wordpress files
      unarchive:
        src: "{{ mount_path }}/acme_wordpress_files.tar.gz"
        dest: "{{ mount_path }}"
        creates: "{{ mount_path }}/wp-config.php"
        remote_src: yes
        mode: '0755'
  

