---
- hosts: word_press # only mount of wordpress servers
  become: true 
  tasks:
    - name: Install nfs client on all instances.
      action: apt pkg=nfs-common state=present
    - name: "Mount nfs server"
      mount: 
          src: "fileserver:{{mount_path}}" 
          path: /home/ubuntu/nfs_fileserver
          fstype: nfs
          state: mounted


