---
- hosts: monitoring
  roles:
  - cloudalchemy.prometheus  
  - cloudalchemy.grafana 
  vars_files:
  - ../secrets/passwords.yml
  vars:

    prometheus_scrape_configs:
    - job_name: "apache"
      file_sd_configs:
      - files:
        - "/etc/prometheus/file_sd/apache.yml"
    - job_name: "node"
      file_sd_configs:
      - files:
        - "/etc/prometheus/file_sd/node.yml"

    prometheus_targets:
      node:
      - targets:
        - "db_master:9100"
        - "db_slave:9100"
        - "db_proxy:9100"
        - "fileserver:9100"
        - "load_balancer:9100"
        - "word_press_01:9100"
        - "word_press_02:9100"
        - "word_press_03:9100"
      apache:
      - targets:
        - "word_press_01:9117"
        - "word_press_02:9117"
        - "word_press_03:9117"



    grafana_security:
      admin_user: admin
      admin_password: "{{grafana_admin_password}}"
    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://localhost:9090'
        basicAuth: false
        
    grafana_dashboards:
      - dashboard_id: 13978
        revision_id: 1
        datasource: prometheus
      - dashboard_id: 3894
        revision_id: 6
        datasource: prometheus
      #https://grafana.com/grafana/dashboards/11269
  
    
        
  

   
   
   