---
- hosts: monitoring
  roles:
  - cloudalchemy.prometheus  
  - cloudalchemy.grafana 
  vars_files:
  - ../secrets/passwords.yml
  vars:
    prometheus_targets:
      node:
      - targets:
        - "{{db_master}}:9100"
        - "{{db_slave}}:9100"
        - "{{db_proxy}}:9100"
        - "{{fileserver}}:9100"
        - "{{load_balancer}}:9100"
        - "{{word_press_01}}:9100"
        - "{{word_press_02}}:9100"
        - "{{word_press_03}}:9100"

    grafana_security:
      admin_user: admin
      admin_password: "{{grafana_admin_password}}"
    grafana_datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: 'http://localhost:9090'
      basicAuth: false
    grafana_dashboards:
        dashboard_id: 111
        revision_id: 1
        datasource: prometheus

  

   
   
   