---
- hosts: word_press
  become: true
  vars_files:
  - ./group_vars/wordpress_default_vars.yml
  - ../secrets/db_password.yml
  tasks:
  - name: Creates www  directory for html files.
    file:
      path: "{{ www_folder }}"
      state: directory

  - name: install php and packages
    package: name={{ php_modules }} update_cache=yes state=latest

  - name: install Apache
    apt: name=apache2 update_cache=yes state=latest

  - name: install acme wordpress and unarchive it
    unarchive:
      src: https://github.com/2dv514/syllabus/blob/master/examination/part_2/acme_wordpress_files_and_data.tar.gz?raw=true
      dest: /home/ubuntu/nfs_fileserver/www
      remote_src: yes

  - name: Unzip wordpress files
    unarchive:
      src: /home/ubuntu/nfs_fileserver/www/acme_wordpress_files.tar.gz
      dest: /home/ubuntu/nfs_fileserver/www
      creates: /home/ubuntu/nfs_fileserver/www/wp-config.php
      remote_src: yes
      mode: '0755'
  
  - name: Replace existing wp-config.php
    template:
      src: "exports/wp-config.php.j2"
      dest: "/home/ubuntu/nfs_fileserver/www/wp-config.php"

  - name: Create document root
    file:
      path: "/var/www/html"
      state: directory
      owner: "{{username}}"
      group: "+{{username}}"
      mode: '0755'
  
  - name: Set up virtual host
    template:
      src: "exports/apache.conf.j2"
      dest: "/etc/apache2/sites-available/apache.conf"
    notify: reload-apache

  - name: Enable rewrite module
    shell: /usr/sbin/a2enmod rewrite
    notify: reload-apache

  - name: Enable new site
    shell: /usr/sbin/a2ensite apache.conf
    notify: reload-apache

  - name: Disable default Apache site
    shell: /usr/sbin/a2dissite 000-default.conf
    notify: restart-apache

  handlers:
  - name: restart-apache
    service:
      name: apache2
      state: restarted

  - name: reload-apache
    service:
      name: apache2
      state: reloaded