---
- hosts: word_press
  become: true
  vars_files:
  - ./group_vars/wordpress_default_vars.yml
  - ../secrets/db_password.yml
  tasks:
  - name: install php and packages
    package: name={{ php_modules }} update_cache=yes state=latest

  - name: install acme wordpress and unarchive it
    unarchive:
      src: https://github.com/2dv514/syllabus/blob/master/examination/part_2/acme_wordpress_files_and_data.tar.gz?raw=true
      dest: /home/ubuntu/nfs_fileserver/www
      remote_src: yes

  # - name: Unzip acme wordpress files and data
  #   unarchive:
  #     src: /home/ubuntu/acme_wordpress_files_and_data.tar.gz
  #     dest: /home/ubuntu/nfs_fileserver/www
  #     remote_src: yes
  #     mode: '0755'

  - name: Unzip wordpress files
    unarchive:
      src: /home/ubuntu/nfs_fileserver/www/acme_wordpress_files.tar.gz
      dest: /home/ubuntu/nfs_fileserver/www
      remote_src: yes
      mode: '0755'
  
  - name: Replace existing wp_config.php
    template:
      src: "exports/wp_config.php.j2"
      dest: "/home/ubuntu/nfs_fileserver/www/wp_config.php"