---
- hosts: word_press
  become: true
  vars_files:
  - ./group_vars/wordpress_default_vars.yml
  - ../secrets/passwords.yml
  tasks:
 
  - name: "Mount nfs server"
    mount: 
      src: "fileserver:{{mount_path}}" 
      path: /home/ubuntu/nfs_fileserver
      fstype: nfs
      state: mounted

  - name: Replace existing wp-config.php
    template:
      src: "exports/wp-config.php.j2"
      dest: "{{ www_folder }}/wp-config.php"

  - name: add .htaccess file
    template:
      src: "exports/.htaccess.j2"
      dest: "{{ www_folder }}/.htaccess"

  - name: Create document root
    file:
      path: "/var/www/html"
      state: directory
      owner: "{{username}}"
      group: "{{username}}"
      mode: '0755'
  
  - name: Set up virtual host
    template:
      src: "exports/apache.conf.j2"
      dest: "/etc/apache2/sites-available/apache.conf"
    notify: reload-apache

  - name: Enable rewrite module
    shell: /usr/sbin/a2enmod rewrite
    notify: reload-apache

  - name: Enable new site
    shell: /usr/sbin/a2ensite apache.conf
    notify: reload-apache

  - name: Disable default Apache site
    shell: /usr/sbin/a2dissite 000-default.conf
    notify: restart-apache

  handlers:
  - name: restart-apache
    service:
      name: apache2
      state: restarted

  - name: reload-apache
    service:
      name: apache2
      state: reloaded